name: Privileged
description: Choose this option if you are @celsiusnarhwal or he asked you directly to create an issue here.
body:
  - type: checkboxes
    id: privileged
    attributes:
      options:
        - label: I'm @celsiusnarhwal or he asked me directly to create an issue here. I understand that my issue will be closed without comment if neither of these things are true.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue
      description: Describe the issue.
