blank_issues_enabled: false
contact_links:
  - name: I have another issue
    about: If you have another issue, such as a feature request or a general support inquiry, start a discussion instead.
    url: https://github.com/celsiusnarhwal/alianator/discussions
