send_messages = "Send Messages and Create Posts"
send_messages_in_threads = "Send Messages in Threads and Posts"
external_emojis = "Use External Emoji"
external_stickers = "Use External Stickers"
manage_emojis = "Manage Guild Expressions"
manage_emojis_and_stickers = "Manage Guild Expressions"
manage_threads = "Manage Threads and Posts"
mention_everyone = "Mention \\@everyone, \\@here, and All Roles"
moderate_members = "Timeout Members"
send_tts_messages = "Send Text-to-Speech Messages"
start_embedded_activities = "Use Activities"
stream = "Video"
use_slash_commands = "Use Application Commands"
use_voice_activation = "Use Voice Activity"
